log:
  output: "file" # whether output to "console" or "file", default is "console"

  # min <= level <= max
  # debug<info<warn<error
  # default: min = max = info
  log_level_min: "warn"
  log_level_max: "error"

  # only apply when output = file
  log_rotation_time: "hour" # day/hour/min, default is "hour"
  log_dir: "log" # Default is "log"
  log_file_name: "logger.log" # Symbolic link file, default is "logger.log"
